Scientific source notebook for the isolated reproduction tree. Calculation cells and saved execution objects are preserved. Narrative navigation has been adapted for this package. Use the reproduction runner and frozen-input prerequisites before executing. Historical evaluation blocks remain reused evidence; this copy does not establish independent replication.

# 05 — Semiconductor downside asymmetry after S and V

**Executed amended study — reused historical evaluation blocks.**

Is an asymmetric semiconductor response useful after ordinary exposure, variance composition, market downside and recent/liquidity risk? A’s sign alone does not answer this forecasting question.

Read with the specified plan, operational specification and data requirements. The calculation functions below are local to this notebook; saved tables retain the comparison and sample identifiers.

## The matched H2 pair and financial interpretation

Compare B+S+V with B+S+V+A on the union of all inputs, including stricter A regime coverage, in both training and evaluation. Refit the baseline here. Positive A adds a negative contribution when u<0, but ordinary slope determines total response; it is not mechanically higher future risk.

In [1]:
from pathlib import Path
import nbformat
ROOT=Path.cwd()
while not (ROOT/'pyproject.toml').exists(): ROOT=ROOT.parent
EXT=ROOT/'extensions/company_risk'
# Execute only tagged definition cells: no earlier notebook scoring or side effects.
shared=nbformat.read(EXT/'notebooks/03_liquidity_recency_calibration.ipynb',4)
for cell in shared.cells:
    if 'shared-company-definitions' in cell.metadata.get('tags',[]): exec(compile(cell.source,'03 shared company definitions','exec'))
features=pd.read_csv(EXT/'data/processed/formation_measurements.csv',parse_dates=['formation_date'])
outcomes=pd.read_csv(EXT/'data/processed/company_outcomes.csv',parse_dates=['formation_date','outcome_end'])
manifest=json.loads((EXT/'specification/comparison_manifest.json').read_text())

runs=[s for s in manifest['runs'] if s['family']=='h2']
def fit_matched_asymmetry_pair(features,outcomes,frozen_runs):
    """Fit every predefined model independently with the shared chronological engine."""
    return run_frozen_company_comparisons(features,outcomes,frozen_runs,'h2')
summary=fit_matched_asymmetry_pair(features,outcomes,runs)

## Primary scoring and amended-register traceability

Retain next-quarter log residual volatility, pooled original observation weights, primary MSE and equal-quarter aggregation; secondary variance QLIKE uses training-only retransformation. Record the change from H2 register conventions and French versus SPY downside. Reused periods do not become new confirmation.

In [2]:
display(summary)

,run_id,baseline_model_id,extended_model_id,block_label,quarters,mean_percentage_gain,conditional_low,conditional_high,mean_absolute_gain,mean_calibration_percentage_gain,mean_dispersion_percentage_gain,mean_qlike_gain,positive_quarter_share,calendar_segments,bootstrap_replications,block_length,seed
0,h2_industry_group,B+S+V,B+S+V+A,all,26,-0.111259,-0.313267,0.065901,-0.000137,0.056062,-0.167321,-0.000800,0.384615,1,2000,4,20261014
1,h2_industry_group,B+S+V,B+S+V+A,confirmation,6,-0.048948,-0.194718,0.096822,-0.000044,0.035844,-0.084792,-0.000178,0.333333,1,2000,4,20261014
2,h2_industry_group,B+S+V,B+S+V+A,development,12,-0.045802,-0.237714,0.178947,-0.000178,0.083934,-0.129736,-0.001430,0.416667,1,2000,4,20261014
3,h2_industry_group,B+S+V,B+S+V+A,validation,8,-0.256179,-0.525728,0.013371,-0.000147,0.029417,-0.285596,-0.000324,0.375000,1,2000,4,20261014
4,h2_main,B+S+V,B+S+V+A,all,26,-0.085735,-0.234861,0.044973,-0.000145,0.031737,-0.117472,-0.000912,0.384615,1,2000,4,20261014
5,h2_main,B+S+V,B+S+V+A,confirmation,6,-0.028791,-0.123815,0.066232,-0.000024,0.032815,-0.061606,-0.000098,0.166667,1,2000,4,20261014
6,h2_main,B+S+V,B+S+V+A,development,12,-0.036360,-0.192144,0.134275,-0.000224,0.040152,-0.076513,-0.001769,0.500000,1,2000,4,20261014
7,h2_main,B+S+V,B+S+V+A,validation,8,-0.202506,-0.404354,-0.000659,-0.000116,0.018305,-0.220811,-0.000238,0.375000,1,2000,4,20261014
8,h2_window252,B+S+V,B+S+V+A,all,26,-0.110881,-0.405800,0.107460,-0.000082,-0.050066,-0.060816,-0.000881,0.576923,1,2000,4,20261014
9,h2_window252,B+S+V,B+S+V+A,confirmation,6,0.074595,-0.091873,0.241064,0.000049,0.105098,-0.030502,0.000156,0.666667,1,2000,4,20261014
10,h2_window252,B+S+V,B+S+V+A,development,12,-0.363490,-0.821163,-0.041209,-0.000255,-0.146936,-0.216554,-0.002265,0.416667,1,2000,4,20261014
11,h2_window252,B+S+V,B+S+V+A,validation,8,0.128925,0.002568,0.255281,0.000079,-0.021132,0.150057,0.000417,0.750000,1,2000,4,20261014

## Predefined robustness and boundaries

Repeat only the H2 pair with industry groups and separately the 252-session exposure window. The joint B versus B+S+V+A contrast is descriptive on the H2 common sample, not a substitute for the staged pairs. No horizon cross-grid, H3 interactions or H4 delayed dependence.

In [3]:
display(summary[summary.block_label.eq('all')])

,run_id,baseline_model_id,extended_model_id,block_label,quarters,mean_percentage_gain,conditional_low,conditional_high,mean_absolute_gain,mean_calibration_percentage_gain,mean_dispersion_percentage_gain,mean_qlike_gain,positive_quarter_share,calendar_segments,bootstrap_replications,block_length,seed
0,h2_industry_group,B+S+V,B+S+V+A,all,26,-0.111259,-0.313267,0.065901,-0.000137,0.056062,-0.167321,-0.000800,0.384615,1,2000,4,20261014
4,h2_main,B+S+V,B+S+V+A,all,26,-0.085735,-0.234861,0.044973,-0.000145,0.031737,-0.117472,-0.000912,0.384615,1,2000,4,20261014
8,h2_window252,B+S+V,B+S+V+A,all,26,-0.110881,-0.405800,0.107460,-0.000082,-0.050066,-0.060816,-0.000881,0.576923,1,2000,4,20261014

## Findings and interpretation

## Bridge through the study

Previous: 04 S/V distinguishes direction and variance composition before A.

Next: 06 Portfolio application is separate, using daily return covariances rather than these company forecasts. Company conclusions can stand alone in 07.

In [4]:
display(summary)

,run_id,baseline_model_id,extended_model_id,block_label,quarters,mean_percentage_gain,conditional_low,conditional_high,mean_absolute_gain,mean_calibration_percentage_gain,mean_dispersion_percentage_gain,mean_qlike_gain,positive_quarter_share,calendar_segments,bootstrap_replications,block_length,seed
0,h2_industry_group,B+S+V,B+S+V+A,all,26,-0.111259,-0.313267,0.065901,-0.000137,0.056062,-0.167321,-0.000800,0.384615,1,2000,4,20261014
1,h2_industry_group,B+S+V,B+S+V+A,confirmation,6,-0.048948,-0.194718,0.096822,-0.000044,0.035844,-0.084792,-0.000178,0.333333,1,2000,4,20261014
2,h2_industry_group,B+S+V,B+S+V+A,development,12,-0.045802,-0.237714,0.178947,-0.000178,0.083934,-0.129736,-0.001430,0.416667,1,2000,4,20261014
3,h2_industry_group,B+S+V,B+S+V+A,validation,8,-0.256179,-0.525728,0.013371,-0.000147,0.029417,-0.285596,-0.000324,0.375000,1,2000,4,20261014
4,h2_main,B+S+V,B+S+V+A,all,26,-0.085735,-0.234861,0.044973,-0.000145,0.031737,-0.117472,-0.000912,0.384615,1,2000,4,20261014
5,h2_main,B+S+V,B+S+V+A,confirmation,6,-0.028791,-0.123815,0.066232,-0.000024,0.032815,-0.061606,-0.000098,0.166667,1,2000,4,20261014
6,h2_main,B+S+V,B+S+V+A,development,12,-0.036360,-0.192144,0.134275,-0.000224,0.040152,-0.076513,-0.001769,0.500000,1,2000,4,20261014
7,h2_main,B+S+V,B+S+V+A,validation,8,-0.202506,-0.404354,-0.000659,-0.000116,0.018305,-0.220811,-0.000238,0.375000,1,2000,4,20261014
8,h2_window252,B+S+V,B+S+V+A,all,26,-0.110881,-0.405800,0.107460,-0.000082,-0.050066,-0.060816,-0.000881,0.576923,1,2000,4,20261014
9,h2_window252,B+S+V,B+S+V+A,confirmation,6,0.074595,-0.091873,0.241064,0.000049,0.105098,-0.030502,0.000156,0.666667,1,2000,4,20261014
10,h2_window252,B+S+V,B+S+V+A,development,12,-0.363490,-0.821163,-0.041209,-0.000255,-0.146936,-0.216554,-0.002265,0.416667,1,2000,4,20261014
11,h2_window252,B+S+V,B+S+V+A,validation,8,0.128925,0.002568,0.255281,0.000079,-0.021132,0.150057,0.000417,0.750000,1,2000,4,20261014