# Semiconductor exposure

These are executed preliminary results with retrospective explanation; full independent replication has not been established. Historical evaluation blocks were reused; they are not fresh holdouts.

Read the saved outputs without executing this notebook. Original code cells, their metadata, execution counts and outputs are preserved. This package supplies selected scientific evidence and context; the code retains its original source environment and frozen-input dependencies. It is not a standalone reproduction environment. See the [notebook index](README.md).

### Context: direction and variance are different hypotheses

This chapter asks whether signed S or nonnegative V adds useful future-risk information **after** B. A negative S can still produce positive V because V squares the loading and scales by historical residualized-SMH variance. This is a test of variance composition beyond total trailing/recent risk, not a forecast of future SMH shock variance.

Fit B, B+S, B+V and B+S+V separately on their full union-input sample. Do not credit a feature for a change in membership. The primary set scores 26 quarters, 2020Q1–2026Q2, 464–494 issuers per quarter; its actual sample ID matches the main calibration set here. The shorter-window alternative uses a different eligible set.

## Research question: Signed exposure and the variance component

**Historical evaluation; the periods have been inspected and reused.**

Does semiconductor direction or estimated historical variance exposure add information beyond B? Both positive and negative loadings can transmit variance; a weak signed S result does not settle V.

The saved calculations retain comparison and sample identifiers.

## Direction, variance and their conditional increments

Separately fit B, B+S, B+V and B+S+V on the same union-input sample. Required pairs: B vs B+S, B vs B+V, B+S vs joint, B+V vs joint. Refit B if S/V eligibility reduces coverage; never attribute different-sample score changes to a feature. Keep conventional loadings in C.

In [1]:
from pathlib import Path
import nbformat
ROOT=Path.cwd()
while not (ROOT/'pyproject.toml').exists(): ROOT=ROOT.parent
EXT=ROOT/'extensions/company_risk'
# Execute only tagged definition cells: no earlier notebook scoring or side effects.
shared=nbformat.read(EXT/'notebooks/03_liquidity_recency_calibration.ipynb',4)
for cell in shared.cells:
    if 'shared-company-definitions' in cell.metadata.get('tags',[]): exec(compile(cell.source,'03 shared company definitions','exec'))
features=pd.read_csv(EXT/'data/processed/formation_measurements.csv',parse_dates=['formation_date'])
outcomes=pd.read_csv(EXT/'data/processed/company_outcomes.csv',parse_dates=['formation_date','outcome_end'])
manifest=json.loads((EXT/'specification/comparison_manifest.json').read_text())

runs=[s for s in manifest['runs'] if s['family'] in ['semiconductor','matched_horizon_semiconductor']]
primary=next(s for s in runs if s['run_id']=='semiconductor_main')
runs.append(dict(primary,run_id='jointSV_matchedMixed',models=['B','B+S+V'],pairs=[['B','B+S+V']]))
def fit_semiconductor_comparison_set(features,outcomes,frozen_runs):
    """Fit every predefined model independently with the shared chronological engine."""
    return run_frozen_company_comparisons(features,outcomes,frozen_runs,'semiconductor')
summary=fit_semiconductor_comparison_set(features,outcomes,runs)

## Does composition add information beyond risk level?

V is a historical component of conventional residual variance and can overlap mechanically with long risk and R. Its coefficient in the company forecast differs from daily-return loadings S and A. A useful V forecast increment would show conditional predictive information, not a pure causal shock or forecast of future SMH variance.

In [2]:
display(summary)

,run_id,baseline_model_id,extended_model_id,block_label,quarters,mean_percentage_gain,conditional_low,conditional_high,mean_absolute_gain,mean_calibration_percentage_gain,mean_dispersion_percentage_gain,mean_qlike_gain,positive_quarter_share,calendar_segments,bootstrap_replications,block_length,seed
0,jointSV_matchedL252,B,B+S+V,all,26,-0.112956,-0.514224,0.244878,-0.000309,-0.142844,0.029888,-0.001104,0.500000,1,2000,4,20261014
1,jointSV_matchedL252,B,B+S+V,confirmation,6,-0.493335,-0.865826,-0.131774,-0.000474,-0.333672,-0.159663,-0.000993,0.000000,1,2000,4,20261014
2,jointSV_matchedL252,B,B+S+V,development,12,-0.258769,-0.778210,0.214548,-0.000603,-0.224551,-0.034218,-0.002384,0.500000,1,2000,4,20261014
3,jointSV_matchedL252,B,B+S+V,validation,8,0.391049,0.139306,0.642791,0.000257,0.122839,0.268209,0.000732,0.875000,1,2000,4,20261014
4,jointSV_matchedL60,B,B+S+V,all,26,-0.077044,-0.456478,0.280540,-0.000320,-0.128838,0.051794,-0.001320,0.500000,1,2000,4,20261014
5,jointSV_matchedL60,B,B+S+V,confirmation,6,-0.549576,-0.917484,-0.166616,-0.000519,-0.347776,-0.201800,-0.001133,0.000000,1,2000,4,20261014
6,jointSV_matchedL60,B,B+S+V,development,12,-0.165693,-0.626512,0.297299,-0.000620,-0.206007,0.040314,-0.002809,0.500000,1,2000,4,20261014
7,jointSV_matchedL60,B,B+S+V,validation,8,0.410329,0.137939,0.682719,0.000277,0.151120,0.259209,0.000773,0.875000,1,2000,4,20261014
8,jointSV_matchedMixed,B,B+S+V,all,26,-0.131650,-0.566221,0.256997,-0.000352,-0.170731,0.039080,-0.001238,0.538462,1,2000,4,20261014
9,jointSV_matchedMixed,B,B+S+V,confirmation,6,-0.538963,-0.904572,-0.167023,-0.000513,-0.357454,-0.181509,-0.001099,0.000000,1,2000,4,20261014
10,jointSV_matchedMixed,B,B+S+V,development,12,-0.281327,-0.857038,0.266123,-0.000687,-0.277104,-0.004223,-0.002633,0.583333,1,2000,4,20261014
11,jointSV_matchedMixed,B,B+S+V,validation,8,0.398349,0.173236,0.623463,0.000271,0.128872,0.269478,0.000751,0.875000,1,2000,4,20261014
12,semiconductor_industry_group,B,B+S,all,26,-0.052506,-0.201100,0.073350,-0.000049,-0.042479,-0.010027,-0.000078,0.346154,1,2000,4,20261014
13,semiconductor_industry_group,B,B+S,confirmation,6,-0.135916,-0.193148,-0.078684,-0.000111,-0.025240,-0.110676,-0.000121,0.166667,1,2000,4,20261014
14,semiconductor_industry_group,B,B+S,development,12,-0.095059,-0.376944,0.158245,-0.000085,-0.094808,-0.000252,-0.000176,0.166667,1,2000,4,20261014
15,semiconductor_industry_group,B,B+S,validation,8,0.073882,0.035185,0.112578,0.000053,0.023085,0.050797,0.000103,0.750000,1,2000,4,20261014
16,semiconductor_industry_group,B,B+V,all,26,-0.072494,-0.168909,0.024541,-0.000193,-0.050926,-0.021568,-0.001063,0.461538,1,2000,4,20261014
17,semiconductor_industry_group,B,B+V,confirmation,6,-0.032631,-0.187324,0.107560,-0.000060,-0.132182,0.099550,-0.000075,0.666667,1,2000,4,20261014
18,semiconductor_industry_group,B,B+V,development,12,-0.113914,-0.226298,0.001466,-0.000357,-0.056831,-0.057083,-0.002235,0.333333,1,2000,4,20261014
19,semiconductor_industry_group,B,B+V,validation,8,-0.040263,-0.209148,0.128622,-0.000046,0.018872,-0.059135,-0.000047,0.500000,1,2000,4,20261014
20,semiconductor_industry_group,B+S,B+S+V,all,26,-0.050801,-0.211495,0.098982,-0.000213,-0.111993,0.061193,-0.001212,0.576923,1,2000,4,20261014
21,semiconductor_industry_group,B+S,B+S+V,confirmation,6,-0.107375,-0.423690,0.203635,-0.000151,-0.301715,0.194340,-0.000159,0.500000,1,2000,4,20261014
22,semiconductor_industry_group,B+S,B+S+V,development,12,-0.067602,-0.189133,0.059121,-0.000377,-0.123078,0.055476,-0.002609,0.500000,1,2000,4,20261014
23,semiconductor_industry_group,B+S,B+S+V,validation,8,0.016833,-0.253768,0.287434,-0.000013,0.046925,-0.030092,0.000092,0.750000,1,2000,4,20261014
24,semiconductor_industry_group,B+V,B+S+V,all,26,-0.030833,-0.191121,0.133231,-0.000069,-0.103804,0.072971,-0.000226,0.423077,1,2000,4,20261014
25,semiconductor_industry_group,B+V,B+S+V,confirmation,6,-0.210413,-0.423279,-0.009107,-0.000203,-0.194848,-0.015564,-0.000204,0.166667,1,2000,4,20261014
26,semiconductor_industry_group,B+V,B+S+V,development,12,-0.049105,-0.295997,0.194512,-0.000105,-0.161618,0.112513,-0.000550,0.333333,1,2000,4,20261014
27,semiconductor_industry_group,B+V,B+S+V,validation,8,0.131259,-0.025317,0.287835,0.000086,0.051199,0.080060,0.000243,0.750000,1,2000,4,20261014
28,semiconductor_main,B,B+S,all,26,-0.094897,-0.510945,0.281364,-0.000184,-0.046840,-0.048057,-0.000229,0.500000,1,2000,4,20261014
29,semiconductor_main,B,B+S,confirmation,6,-0.461437,-0.705059,-0.177469,-0.000418,-0.197771,-0.263666,-0.001025,0.000000,1,2000,4,20261014
30,semiconductor_main,B,B+S,development,12,-0.245738,-0.912162,0.371400,-0.000385,-0.080605,-0.165133,-0.000482,0.583333,1,2000,4,20261014
31,semiconductor_main,B,B+S,validation,8,0.406268,0.270894,0.541641,0.000292,0.117005,0.289263,0.000747,0.750000,1,2000,4,20261014
32,semiconductor_main,B,B+V,all,26,-0.062678,-0.227341,0.106839,-0.000083,0.004678,-0.067355,-0.000440,0.538462,1,2000,4,20261014
33,semiconductor_main,B,B+V,confirmation,6,-0.028878,-0.222469,0.193751,0.000007,0.222218,-0.251096,-0.000296,0.666667,1,2000,4,20261014
34,semiconductor_main,B,B+V,development,12,-0.133754,-0.389949,0.179825,-0.000204,-0.085637,-0.048117,-0.000812,0.500000,1,2000,4,20261014
35,semiconductor_main,B,B+V,validation,8,0.018588,-0.204699,0.241874,0.000030,-0.023005,0.041593,0.000010,0.500000,1,2000,4,20261014
36,semiconductor_main,B+S,B+S+V,all,26,-0.037069,-0.192525,0.120053,-0.000168,-0.124002,0.086933,-0.001008,0.423077,1,2000,4,20261014
37,semiconductor_main,B+S,B+S+V,confirmation,6,-0.076521,-0.225458,0.044951,-0.000095,-0.158604,0.082084,-0.000075,0.333333,1,2000,4,20261014
38,semiconductor_main,B+S,B+S+V,development,12,-0.036541,-0.278032,0.246405,-0.000302,-0.197303,0.160762,-0.002150,0.250000,1,2000,4,20261014
39,semiconductor_main,B+S,B+S+V,validation,8,-0.008272,-0.235030,0.218485,-0.000021,0.011902,-0.020174,0.000004,0.750000,1,2000,4,20261014
40,semiconductor_main,B+V,B+S+V,all,26,-0.068197,-0.459246,0.287463,-0.000269,-0.174824,0.106626,-0.000798,0.500000,1,2000,4,20261014
41,semiconductor_main,B+V,B+S+V,confirmation,6,-0.511735,-1.085840,0.019584,-0.000520,-0.580623,0.068888,-0.000804,0.333333,1,2000,4,20261014
42,semiconductor_main,B+V,B+S+V,development,12,-0.144253,-0.556287,0.211605,-0.000483,-0.189213,0.044960,-0.001821,0.416667,1,2000,4,20261014
43,semiconductor_main,B+V,B+S+V,validation,8,0.378540,-0.037850,0.794930,0.000241,0.151110,0.227430,0.000741,0.750000,1,2000,4,20261014
44,semiconductor_window252,B,B+S,all,26,-0.094044,-0.392748,0.210510,-0.000132,-0.082628,-0.011416,0.000015,0.423077,1,2000,4,20261014
45,semiconductor_window252,B,B+S,confirmation,6,-0.460488,-0.898156,-0.049895,-0.000433,-0.291637,-0.168851,-0.000911,0.166667,1,2000,4,20261014
46,semiconductor_window252,B,B+S,development,12,-0.132735,-0.554247,0.304371,-0.000179,-0.030366,-0.102369,0.000221,0.500000,1,2000,4,20261014
47,semiconductor_window252,B,B+S,validation,8,0.238826,0.027578,0.450075,0.000166,-0.004265,0.243092,0.000402,0.500000,1,2000,4,20261014
48,semiconductor_window252,B,B+V,all,26,0.132799,-0.051071,0.307288,0.000090,0.078802,0.053998,-0.000155,0.615385,1,2000,4,20261014
49,semiconductor_window252,B,B+V,confirmation,6,0.171040,-0.107195,0.416486,0.000187,0.332484,-0.161444,-0.000125,0.666667,1,2000,4,20261014
50,semiconductor_window252,B,B+V,development,12,0.102542,-0.210757,0.472044,0.000033,0.032049,0.070493,-0.000344,0.500000,1,2000,4,20261014
51,semiconductor_window252,B,B+V,validation,8,0.149506,-0.048743,0.347754,0.000104,-0.041331,0.190837,0.000105,0.750000,1,2000,4,20261014
52,semiconductor_window252,B+S,B+S+V,all,26,0.005419,-0.126588,0.155090,-0.000078,0.048131,-0.042712,-0.000632,0.461538,1,2000,4,20261014
53,semiconductor_window252,B+S,B+S+V,confirmation,6,0.306879,-0.016904,0.619120,0.000287,0.348174,-0.041295,0.000278,0.666667,1,2000,4,20261014
54,semiconductor_window252,B+S,B+S+V,development,12,-0.132809,-0.305221,0.011131,-0.000309,-0.054671,-0.078137,-0.001467,0.333333,1,2000,4,20261014
55,semiconductor_window252,B+S,B+S+V,validation,8,-0.013333,-0.034552,0.007886,-0.000007,-0.022698,0.009365,-0.000062,0.500000,1,2000,4,20261014
56,semiconductor_window252,B+V,B+S+V,all,26,-0.221678,-0.463320,-0.018159,-0.000300,-0.112903,-0.108775,-0.000461,0.500000,1,2000,4,20261014
57,semiconductor_window252,B+V,B+S+V,confirmation,6,-0.323990,-0.742159,0.094179,-0.000333,-0.274420,-0.049570,-0.000509,0.500000,1,2000,4,20261014
58,semiconductor_window252,B+V,B+S+V,development,12,-0.369091,-0.596385,-0.140535,-0.000521,-0.117195,-0.251897,-0.000901,0.416667,1,2000,4,20261014
59,semiconductor_window252,B+V,B+S+V,validation,8,0.076176,-0.039359,0.191711,0.000055,0.014671,0.061505,0.000234,0.625000,1,2000,4,20261014

### Read the main four pairs separately

| Primary pair | Mean quarterly MSE gain (%) | Conditional 95% interval (%) |
|---|---:|---:|
| B→B+S | −0.095 | [−0.511,0.281] |
| B→B+V | −0.063 | [−0.227,0.107] |
| B+S→B+S+V | −0.037 | [−0.193,0.120] |
| B+V→B+S+V | −0.068 | [−0.459,0.287] |

Source: company_inference.csv, `semiconductor_main`, `block_label=all`. Positive means lower unsmeared log-volatility MSE. All four estimates are unfavorable and intervals span zero. The descriptive common-horizon joint bridge `jointSV_matchedMixed`, B→B+S+V, is **−0.132% [−0.566,0.257]**. Do not add mean percentage increments with different quarterly denominators.

The primary S comparison gains **+0.406%** in validation but **−0.461% [−0.705,−0.177]** in confirmation. V's corresponding means are +0.019% and −0.029%, both uncertain. One favorable block cannot establish stability.

## Bounded robustness without a search grid

Repeat the named four pairs under industry-group controls and separately the 252-session exposure window, one change at a time. Joint B vs B+S+V is the fixed semiconductor matched-liquidity-horizon check, on common samples; retain primary mixed L as the bridge. Do not cross all robustness dimensions.

In [3]:
display(summary[summary.block_label.eq('all')])

,run_id,baseline_model_id,extended_model_id,block_label,quarters,mean_percentage_gain,conditional_low,conditional_high,mean_absolute_gain,mean_calibration_percentage_gain,mean_dispersion_percentage_gain,mean_qlike_gain,positive_quarter_share,calendar_segments,bootstrap_replications,block_length,seed
0,jointSV_matchedL252,B,B+S+V,all,26,-0.112956,-0.514224,0.244878,-0.000309,-0.142844,0.029888,-0.001104,0.500000,1,2000,4,20261014
4,jointSV_matchedL60,B,B+S+V,all,26,-0.077044,-0.456478,0.280540,-0.000320,-0.128838,0.051794,-0.001320,0.500000,1,2000,4,20261014
8,jointSV_matchedMixed,B,B+S+V,all,26,-0.131650,-0.566221,0.256997,-0.000352,-0.170731,0.039080,-0.001238,0.538462,1,2000,4,20261014
12,semiconductor_industry_group,B,B+S,all,26,-0.052506,-0.201100,0.073350,-0.000049,-0.042479,-0.010027,-0.000078,0.346154,1,2000,4,20261014
16,semiconductor_industry_group,B,B+V,all,26,-0.072494,-0.168909,0.024541,-0.000193,-0.050926,-0.021568,-0.001063,0.461538,1,2000,4,20261014
20,semiconductor_industry_group,B+S,B+S+V,all,26,-0.050801,-0.211495,0.098982,-0.000213,-0.111993,0.061193,-0.001212,0.576923,1,2000,4,20261014
24,semiconductor_industry_group,B+V,B+S+V,all,26,-0.030833,-0.191121,0.133231,-0.000069,-0.103804,0.072971,-0.000226,0.423077,1,2000,4,20261014
28,semiconductor_main,B,B+S,all,26,-0.094897,-0.510945,0.281364,-0.000184,-0.046840,-0.048057,-0.000229,0.500000,1,2000,4,20261014
32,semiconductor_main,B,B+V,all,26,-0.062678,-0.227341,0.106839,-0.000083,0.004678,-0.067355,-0.000440,0.538462,1,2000,4,20261014
36,semiconductor_main,B+S,B+S+V,all,26,-0.037069,-0.192525,0.120053,-0.000168,-0.124002,0.086933,-0.001008,0.423077,1,2000,4,20261014
40,semiconductor_main,B+V,B+S+V,all,26,-0.068197,-0.459246,0.287463,-0.000269,-0.174824,0.106626,-0.000798,0.500000,1,2000,4,20261014
44,semiconductor_window252,B,B+S,all,26,-0.094044,-0.392748,0.210510,-0.000132,-0.082628,-0.011416,0.000015,0.423077,1,2000,4,20261014
48,semiconductor_window252,B,B+V,all,26,0.132799,-0.051071,0.307288,0.000090,0.078802,0.053998,-0.000155,0.615385,1,2000,4,20261014
52,semiconductor_window252,B+S,B+S+V,all,26,0.005419,-0.126588,0.155090,-0.000078,0.048131,-0.042712,-0.000632,0.461538,1,2000,4,20261014
56,semiconductor_window252,B+V,B+S+V,all,26,-0.221678,-0.463320,-0.018159,-0.000300,-0.112903,-0.108775,-0.000461,0.500000,1,2000,4,20261014

### Bounded alternatives: keep favorable and unfavorable evidence

![Semiconductor and asymmetry sensitivity intervals](assets/semiconductor-exposure-semiconductor_sensitivities.png)

The first two panels show all four S/V pairs at main 504-session and shorter 252-session settings; the third previews A. Whiskers are saved conditional intervals, not full-pipeline uncertainty. The horizontal intervals are conditional on the saved fitted inputs and forecasts.

With industry-group rather than sector controls, the four all-period gains are **−0.053%, −0.072%, −0.051%, −0.031%**, all intervals spanning zero. With 252-session exposure measurements they are **−0.094%, +0.133%, +0.005%, −0.222%**, in the same pair order as the table above. The last interval is [−0.463,−0.018]; the favorable V-only estimate spans zero. Shorter-window sets use sample ID `40ed4a5850fad159` and 466–496 issuers per quarter, so main-versus-shorter differences also reflect eligibility.

Fixed horizon joint S/V bridges are −0.132% mixed, −0.077% 60/60 and −0.113% 252/252, all intervals crossing zero. All block/sensitivity rows retain the declared comparisons without a model/horizon search.

## Findings and interpretation

Mean quarterly MSE improvements beyond B are −0.095% for S and −0.063% for V, with conditional intervals [−0.511%, 0.281%] and [−0.227%, 0.107%]. The common-sample joint increment is −0.132%. These small, unstable effects and bounded alternatives do not establish reliable additional semiconductor forecasting value. V represents historical variance composition rather than future shock variance. Negative results and all block labels are retained.

## Related calculations

[Recent risk and liquidity](recent-risk-and-liquidity.ipynb) establishes the benchmark. The supporting [downside-asymmetry calculation](../reproduction/company-risk/extensions/company_risk/notebooks/05_downside_asymmetry.ipynb) asks whether downside exposure adds information after signed exposure and variance composition. Use the reproduction runner to execute that source notebook.

In [4]:
display(summary)

,run_id,baseline_model_id,extended_model_id,block_label,quarters,mean_percentage_gain,conditional_low,conditional_high,mean_absolute_gain,mean_calibration_percentage_gain,mean_dispersion_percentage_gain,mean_qlike_gain,positive_quarter_share,calendar_segments,bootstrap_replications,block_length,seed
0,jointSV_matchedL252,B,B+S+V,all,26,-0.112956,-0.514224,0.244878,-0.000309,-0.142844,0.029888,-0.001104,0.500000,1,2000,4,20261014
1,jointSV_matchedL252,B,B+S+V,confirmation,6,-0.493335,-0.865826,-0.131774,-0.000474,-0.333672,-0.159663,-0.000993,0.000000,1,2000,4,20261014
2,jointSV_matchedL252,B,B+S+V,development,12,-0.258769,-0.778210,0.214548,-0.000603,-0.224551,-0.034218,-0.002384,0.500000,1,2000,4,20261014
3,jointSV_matchedL252,B,B+S+V,validation,8,0.391049,0.139306,0.642791,0.000257,0.122839,0.268209,0.000732,0.875000,1,2000,4,20261014
4,jointSV_matchedL60,B,B+S+V,all,26,-0.077044,-0.456478,0.280540,-0.000320,-0.128838,0.051794,-0.001320,0.500000,1,2000,4,20261014
5,jointSV_matchedL60,B,B+S+V,confirmation,6,-0.549576,-0.917484,-0.166616,-0.000519,-0.347776,-0.201800,-0.001133,0.000000,1,2000,4,20261014
6,jointSV_matchedL60,B,B+S+V,development,12,-0.165693,-0.626512,0.297299,-0.000620,-0.206007,0.040314,-0.002809,0.500000,1,2000,4,20261014
7,jointSV_matchedL60,B,B+S+V,validation,8,0.410329,0.137939,0.682719,0.000277,0.151120,0.259209,0.000773,0.875000,1,2000,4,20261014
8,jointSV_matchedMixed,B,B+S+V,all,26,-0.131650,-0.566221,0.256997,-0.000352,-0.170731,0.039080,-0.001238,0.538462,1,2000,4,20261014
9,jointSV_matchedMixed,B,B+S+V,confirmation,6,-0.538963,-0.904572,-0.167023,-0.000513,-0.357454,-0.181509,-0.001099,0.000000,1,2000,4,20261014
10,jointSV_matchedMixed,B,B+S+V,development,12,-0.281327,-0.857038,0.266123,-0.000687,-0.277104,-0.004223,-0.002633,0.583333,1,2000,4,20261014
11,jointSV_matchedMixed,B,B+S+V,validation,8,0.398349,0.173236,0.623463,0.000271,0.128872,0.269478,0.000751,0.875000,1,2000,4,20261014
12,semiconductor_industry_group,B,B+S,all,26,-0.052506,-0.201100,0.073350,-0.000049,-0.042479,-0.010027,-0.000078,0.346154,1,2000,4,20261014
13,semiconductor_industry_group,B,B+S,confirmation,6,-0.135916,-0.193148,-0.078684,-0.000111,-0.025240,-0.110676,-0.000121,0.166667,1,2000,4,20261014
14,semiconductor_industry_group,B,B+S,development,12,-0.095059,-0.376944,0.158245,-0.000085,-0.094808,-0.000252,-0.000176,0.166667,1,2000,4,20261014
15,semiconductor_industry_group,B,B+S,validation,8,0.073882,0.035185,0.112578,0.000053,0.023085,0.050797,0.000103,0.750000,1,2000,4,20261014
16,semiconductor_industry_group,B,B+V,all,26,-0.072494,-0.168909,0.024541,-0.000193,-0.050926,-0.021568,-0.001063,0.461538,1,2000,4,20261014
17,semiconductor_industry_group,B,B+V,confirmation,6,-0.032631,-0.187324,0.107560,-0.000060,-0.132182,0.099550,-0.000075,0.666667,1,2000,4,20261014
18,semiconductor_industry_group,B,B+V,development,12,-0.113914,-0.226298,0.001466,-0.000357,-0.056831,-0.057083,-0.002235,0.333333,1,2000,4,20261014
19,semiconductor_industry_group,B,B+V,validation,8,-0.040263,-0.209148,0.128622,-0.000046,0.018872,-0.059135,-0.000047,0.500000,1,2000,4,20261014
20,semiconductor_industry_group,B+S,B+S+V,all,26,-0.050801,-0.211495,0.098982,-0.000213,-0.111993,0.061193,-0.001212,0.576923,1,2000,4,20261014
21,semiconductor_industry_group,B+S,B+S+V,confirmation,6,-0.107375,-0.423690,0.203635,-0.000151,-0.301715,0.194340,-0.000159,0.500000,1,2000,4,20261014
22,semiconductor_industry_group,B+S,B+S+V,development,12,-0.067602,-0.189133,0.059121,-0.000377,-0.123078,0.055476,-0.002609,0.500000,1,2000,4,20261014
23,semiconductor_industry_group,B+S,B+S+V,validation,8,0.016833,-0.253768,0.287434,-0.000013,0.046925,-0.030092,0.000092,0.750000,1,2000,4,20261014
24,semiconductor_industry_group,B+V,B+S+V,all,26,-0.030833,-0.191121,0.133231,-0.000069,-0.103804,0.072971,-0.000226,0.423077,1,2000,4,20261014
25,semiconductor_industry_group,B+V,B+S+V,confirmation,6,-0.210413,-0.423279,-0.009107,-0.000203,-0.194848,-0.015564,-0.000204,0.166667,1,2000,4,20261014
26,semiconductor_industry_group,B+V,B+S+V,development,12,-0.049105,-0.295997,0.194512,-0.000105,-0.161618,0.112513,-0.000550,0.333333,1,2000,4,20261014
27,semiconductor_industry_group,B+V,B+S+V,validation,8,0.131259,-0.025317,0.287835,0.000086,0.051199,0.080060,0.000243,0.750000,1,2000,4,20261014
28,semiconductor_main,B,B+S,all,26,-0.094897,-0.510945,0.281364,-0.000184,-0.046840,-0.048057,-0.000229,0.500000,1,2000,4,20261014
29,semiconductor_main,B,B+S,confirmation,6,-0.461437,-0.705059,-0.177469,-0.000418,-0.197771,-0.263666,-0.001025,0.000000,1,2000,4,20261014
30,semiconductor_main,B,B+S,development,12,-0.245738,-0.912162,0.371400,-0.000385,-0.080605,-0.165133,-0.000482,0.583333,1,2000,4,20261014
31,semiconductor_main,B,B+S,validation,8,0.406268,0.270894,0.541641,0.000292,0.117005,0.289263,0.000747,0.750000,1,2000,4,20261014
32,semiconductor_main,B,B+V,all,26,-0.062678,-0.227341,0.106839,-0.000083,0.004678,-0.067355,-0.000440,0.538462,1,2000,4,20261014
33,semiconductor_main,B,B+V,confirmation,6,-0.028878,-0.222469,0.193751,0.000007,0.222218,-0.251096,-0.000296,0.666667,1,2000,4,20261014
34,semiconductor_main,B,B+V,development,12,-0.133754,-0.389949,0.179825,-0.000204,-0.085637,-0.048117,-0.000812,0.500000,1,2000,4,20261014
35,semiconductor_main,B,B+V,validation,8,0.018588,-0.204699,0.241874,0.000030,-0.023005,0.041593,0.000010,0.500000,1,2000,4,20261014
36,semiconductor_main,B+S,B+S+V,all,26,-0.037069,-0.192525,0.120053,-0.000168,-0.124002,0.086933,-0.001008,0.423077,1,2000,4,20261014
37,semiconductor_main,B+S,B+S+V,confirmation,6,-0.076521,-0.225458,0.044951,-0.000095,-0.158604,0.082084,-0.000075,0.333333,1,2000,4,20261014
38,semiconductor_main,B+S,B+S+V,development,12,-0.036541,-0.278032,0.246405,-0.000302,-0.197303,0.160762,-0.002150,0.250000,1,2000,4,20261014
39,semiconductor_main,B+S,B+S+V,validation,8,-0.008272,-0.235030,0.218485,-0.000021,0.011902,-0.020174,0.000004,0.750000,1,2000,4,20261014
40,semiconductor_main,B+V,B+S+V,all,26,-0.068197,-0.459246,0.287463,-0.000269,-0.174824,0.106626,-0.000798,0.500000,1,2000,4,20261014
41,semiconductor_main,B+V,B+S+V,confirmation,6,-0.511735,-1.085840,0.019584,-0.000520,-0.580623,0.068888,-0.000804,0.333333,1,2000,4,20261014
42,semiconductor_main,B+V,B+S+V,development,12,-0.144253,-0.556287,0.211605,-0.000483,-0.189213,0.044960,-0.001821,0.416667,1,2000,4,20261014
43,semiconductor_main,B+V,B+S+V,validation,8,0.378540,-0.037850,0.794930,0.000241,0.151110,0.227430,0.000741,0.750000,1,2000,4,20261014
44,semiconductor_window252,B,B+S,all,26,-0.094044,-0.392748,0.210510,-0.000132,-0.082628,-0.011416,0.000015,0.423077,1,2000,4,20261014
45,semiconductor_window252,B,B+S,confirmation,6,-0.460488,-0.898156,-0.049895,-0.000433,-0.291637,-0.168851,-0.000911,0.166667,1,2000,4,20261014
46,semiconductor_window252,B,B+S,development,12,-0.132735,-0.554247,0.304371,-0.000179,-0.030366,-0.102369,0.000221,0.500000,1,2000,4,20261014
47,semiconductor_window252,B,B+S,validation,8,0.238826,0.027578,0.450075,0.000166,-0.004265,0.243092,0.000402,0.500000,1,2000,4,20261014
48,semiconductor_window252,B,B+V,all,26,0.132799,-0.051071,0.307288,0.000090,0.078802,0.053998,-0.000155,0.615385,1,2000,4,20261014
49,semiconductor_window252,B,B+V,confirmation,6,0.171040,-0.107195,0.416486,0.000187,0.332484,-0.161444,-0.000125,0.666667,1,2000,4,20261014
50,semiconductor_window252,B,B+V,development,12,0.102542,-0.210757,0.472044,0.000033,0.032049,0.070493,-0.000344,0.500000,1,2000,4,20261014
51,semiconductor_window252,B,B+V,validation,8,0.149506,-0.048743,0.347754,0.000104,-0.041331,0.190837,0.000105,0.750000,1,2000,4,20261014
52,semiconductor_window252,B+S,B+S+V,all,26,0.005419,-0.126588,0.155090,-0.000078,0.048131,-0.042712,-0.000632,0.461538,1,2000,4,20261014
53,semiconductor_window252,B+S,B+S+V,confirmation,6,0.306879,-0.016904,0.619120,0.000287,0.348174,-0.041295,0.000278,0.666667,1,2000,4,20261014
54,semiconductor_window252,B+S,B+S+V,development,12,-0.132809,-0.305221,0.011131,-0.000309,-0.054671,-0.078137,-0.001467,0.333333,1,2000,4,20261014
55,semiconductor_window252,B+S,B+S+V,validation,8,-0.013333,-0.034552,0.007886,-0.000007,-0.022698,0.009365,-0.000062,0.500000,1,2000,4,20261014
56,semiconductor_window252,B+V,B+S+V,all,26,-0.221678,-0.463320,-0.018159,-0.000300,-0.112903,-0.108775,-0.000461,0.500000,1,2000,4,20261014
57,semiconductor_window252,B+V,B+S+V,confirmation,6,-0.323990,-0.742159,0.094179,-0.000333,-0.274420,-0.049570,-0.000509,0.500000,1,2000,4,20261014
58,semiconductor_window252,B+V,B+S+V,development,12,-0.369091,-0.596385,-0.140535,-0.000521,-0.117195,-0.251897,-0.000901,0.416667,1,2000,4,20261014
59,semiconductor_window252,B+V,B+S+V,validation,8,0.076176,-0.039359,0.191711,0.000055,0.014671,0.061505,0.000234,0.625000,1,2000,4,20261014

### Takeaway and next question

These saved comparisons do not establish stable added semiconductor forecasting value after B. They do not deny historical semiconductor-related variation: V is partly a decomposition of risk already represented by long risk/R. A null or adverse increment means that identifying this component has not demonstrated extra predictive usefulness here. The supporting downside-asymmetry comparison tests A after S and V, refitting the baseline on the sample eligible for A.